export { default as BeSwitch } from './switch'
export { default as BeButton } from './button'
export { default as BeEllipsis } from './ellipsis'
export { default as BeDialog } from './dialog'
export { default as BeLoading } from './loading-plugin'
export { default as BeProgress } from './progress'
export { default as BeTooltip } from './tooltip'
export { default as BeInputNumber } from './input-number'
export { default as BeInput } from './input'
export { default as BeAutocomplete } from './autocomplete'
export { default as BeIcon } from './icon'
export { default as BeTag } from './tag'
export { default as BePopover } from './popover'
export { default as BePagination } from './pagination'
export { BeContextmenu } from './contextmenu'
export { BeContextmenuItem } from './contextmenu'
export { BeContextmenuSubMenu } from './contextmenu'
export { BeBreadcrumb } from './breadcrumb'
export { BeBreadcrumbItem } from './breadcrumb'
export { BeMain } from './container'
export { BeFooter } from './container'
export { BeAside } from './container'
export { BeHeader } from './container'
export { BeContainer } from './container'
export { BeSelect } from './select'
export { BeSelectMultiple } from './select'
export { BeBackTop } from './backup'
// plugins
export { loadingPlugin as BeLoadingSer } from './loading-plugin' // 服务
export { default as BeNotification } from './notification-plugin' // 服务
export { default as BeMessage } from './message-plugin'
export { default as BeMsg } from './message-box-plugin' // 服务
// function
export * from './icon'
